services:
  master:
    build:
      dockerfile: MasterFile
      context: ./dockerfile
    container_name: master-master
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - HOST_IP_LIST=${HOST_IP_LIST}
    volumes:
      - ../../:/OSIR
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - "default"
      - "all"

  samba:
    tty: true
    network_mode: bridge
    volumes:
      - ./../../share:/Shared
    ports:
      - "139:139"
      - "445:445"
    build:
      context: ../ 
      dockerfile: ./master/dockerfile/SambaFile
    container_name: master-samba
    profiles:
      - "smb"      # Assign samba service to the smb profile
      - "all"

  splunk:
    build:
      context: ./dockerfile
      dockerfile: SplunkFile
    container_name: master-splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=DFIR_passwd
      - SPLUNK_LICENSE_URI=Free
    ports:
      - "8000:8000"  # Splunk web interface
      - "8089:8089"  # Splunk services interface
      - "9997:9997"  # Event listening port
      - "8088:8088"  # HEC port
    volumes: 
      - ../splunk/data/etc/:/opt/splunk/etc
      - ../splunk/data/var/:/opt/splunk/var
      - ../splunk/apps/SA-ADTimeline/:/opt/splunk/etc/apps/SA-ADTimeline/ # ADTimeline app
      - ../splunk/apps/TA_evtx_dump/:/opt/splunk/etc/apps/TA_evtx_dump/ # EVTX dump app
      - ../splunk/apps/DFIR_ORC/:/opt/splunk/etc/apps/DFIR_ORC/ # DFIR ORC app
      - ./dockerfile/sources/default.yml:/tmp/defaults/default.yml # Conffiguration file to enable HEC
    profiles:
      - "splunk"
      - "all"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: master-rabbitmq
    ports:
      - "5672:5672"      # AMQP protocol port
      - "15672:15672"    # Management interface port
    volumes:
      - ./dockerfile/sources/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=dfir
      - RABBITMQ_DEFAULT_PASS=dfir
    restart: unless-stopped
    profiles:
      - "default"
      - "all"

  redis:
    image: redis:latest
    container_name: master-redis
    ports:
      - "6379:6379"      # Redis port
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    profiles:
      - "default"
      - "all"

  flower:
    image: mher/flower
    container_name: master-flower
    command: 
      - "celery"
      - "--broker=amqp://dfir:dfir@rabbitmq:5672//"
      - "--result-backend=redis://redis:6379/0 "
      - "flower"
      - "--broker_api=http://dfir:dfir@rabbitmq:15672/api//"
      - "--port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - FLOWER_UNAUTHENTICATED_API=true
    profiles:
      - "default"
      - "all"

  postgres:
    image: postgres:latest
    container_name: master-postgres
    environment:
      POSTGRES_DB: OSIR_db
      POSTGRES_USER: dfir
      POSTGRES_PASSWORD: dfir
    ports:
      - "5432:5432"
    profiles:
      - "default"
      - "all"

  pgadmin:
    image: dpage/pgadmin4
    container_name: master-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dfir@OSIR.com
      PGADMIN_DEFAULT_PASSWORD: dfir
    ports:
      - "80:80"
    volumes:
      - ./dockerfile/sources/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    profiles:
      - "default"
      - "all"
