version: 1.0
author:
module: chromium
description: Parsing of chromium artifact.
os: windows
type: process
disk_only: False
no_multithread: False
processor_type: 
  - external
processor_os: unix
tool: 
  path: python
  cmd: /OSIR/OSIR/bin/hindsight/hindsight.py --input {input_dir} -o {output_file} -f jsonl
  source:
  version: 
input:
  type: dir
  path: AppData/Local
output:
  type: single_file
  format: jsonl
  output_file: "{endpoint_name}-{input_path_hash}--{module}"
endpoint: "restore_fs\/(.*?)\/"
