version: 1.0
author: author_name
module: module_name
description: module_description
os: module_os
type: module_type
disk_only: False
no_multithread: False
processor_type: 
  - module_processor_type
processor_os: unix
tool:
  path: module_tool_name
  cmd: module_tool_param
input:
  type: module_input_type
  name: module_input_regex
  path: module_input_path
output:
  type: module_output_type
  format: module_output_format
  output_file: module_output_name
endpoint: module_endpoint_regex
