version: 1.0
author: 
module: debug
description: Parsing logs from '/var/log/debug'
os: unix
processing_os: unix
processor_type:
- internal
disk_only: false
no_multithread: false
type: process
processor_os: unix
input:
  type: file
  path: var/log
  name: (?:debug)
output:
  type: single_file
  format: json
  output_file: '{endpoint_name}--{module}-{input_file}.jsonl'
endpoint: extract_uac/(.*?)/
