version: 1.0
author:
description:
os: windows
modules:
  - extract_orc.yml
  - evtx_orc.yml
  - test_process_dir
  - test_process_dir_multiple_output
  - prefetch
  - restore_fs
  - amcache.yml
  - chromium.yml
  - firefox.yml
  - hives_hklm.yml
  - hives_hkcu.yml
  - jump_list.yml
  - lnk.yml
  - recycle_bin.yml
  - shell_bags.yml
  - shimcache.yml
  - srum.yml
  - win_timeline.yml